### ISSUE TITLE
Crash in print in MPI_Reduce, Cray XC30/40

### ISSUE THREAD

**Issue by galfthan** [fmihpc/phiprof#3]
Earlier phiprof has been very stable, but already twice I have encountered the following error on larger production simulations on Cray XC30 and XC40 in the print phase:
```
Rank 314 [Tue Jan 20 11:07:29 2015] [c0-0c1s10n1] Fatal error in PMPI_Reduce: Message truncated, error stack:
PMPI_Reduce(1351).................: MPI_Reduce(sbuf=0x2aaaf0e55000, rbuf=0x2aaafa597000, count=251, MPI_DOUBLE, MPI_SUM, root=0, comm=0xc4000004) failed
MPIR_Reduce_impl(1157)............: 
MPIR_Reduce_intra(951)............: 
MPIR_Reduce_binomial(189).........: 
MPIDI_CH3U_Receive_data_found(153): Message from rank 1 and tag 11 truncated; 2016 bytes received but buffer size is 2008
_pmiu_daemon(SIGCHLD): [NID 00105] [c0-0c1s10n1] [Tue Jan 20 11:07:29 2015] PE RANK 314 exit signal Aborted
[NID 00105] 2015-01-20 11:07:29 Apid 9586734: initiated application termination
```

**Comment by sandroos** [comment]
MPI says that rank=1, tag=11 message was truncated, I guess the reduce somehow overlaps with another communication as you suspected..

**Comment by iljah** [comment]
> MPI says that rank=1, tag=11 message was truncated, I guess the reduce
> somehow overlaps with another communication as you suspected..

I remember dccrg having problems in overlapping isends/ireceives with a 
global comm operation but the global ones don't take a tag as argument 
so shouldn't cause trouble unless mpi is buggy.

**Comment by galfthan** [comment]
Code has changed a lot in 2.0, and this has not been seen for a long time. Closing this now.
