### ISSUE TITLE
Work units

### ISSUE THREAD

**Issue by sandroos** [fmihpc/phiprof#6]
Only the work units reported by master process are taken into account when calculating the statistics (e.g. spatial cells / second in Vlasiator), and the units reported by other processes are ignored. This is awkward to use in practice because the master doesn't know how much other processes compute. So phiprof should ideally sum up the work units to master process for each label.

**Comment by galfthan** [comment]
Well if that was the case it was a bug, all processes (which share the same timer set) should be reported. 

Looking quickly at the code I cannot see any obvious bug, the workunits are collected from all processes here https://github.com/fmihpc/phiprof/blob/master/src/phiprof.cpp#L456 & https://github.com/fmihpc/phiprof/blob/master/src/phiprof.cpp#L484
